# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14fc68f18da7fce0dffcf4977ffaf98f3f00a68cd81610e40cda8f58723f56d847d65a0b8a25654f246e3c92821917088803ce6ced0e58c0e323f744eee56afc

test:
  secret_key_base: e3a5cfe1ac28e1ff040f3106ffd9354a14bc36d5a7c917927381e19643c9d2859ecb53bbd738f95fec5e9e6615fccc6fc354e791b224abb9c1a043a6fcaf4b32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
